source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'RxSwiftNew' do
    pod 'RxSwift', '~> 4.0'
    pod 'RxCocoa', '~> 4.0'
    pod 'MBProgressHUD', '~> 1.0'
    pod 'Kingfisher', '~> 4.0'
    pod 'FLUtilities', :git => 'https://github.com/Nickelfox/FLUtilities.git'
    pod 'FLLogs', :git => 'https://github.com/Nickelfox/FLLogs.git'
end

target 'Model' do
    pod 'FLUtilities', :git => 'https://github.com/Nickelfox/FLUtilities.git'
    pod 'FLLogs', :git => 'https://github.com/Nickelfox/FLLogs.git'
    pod 'FoxAPIKit'
end
